---
backup_gpg_signing_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34376533306637353732363331396161663139633262386237333639353939383763353038666639
          3335343135386462393162333833356333316566626533620a333964633032623330393937356162
          39316438616536396133356562343866306630343434366438666265393863333365656364363761
          3430313564333362370a643761353739336133323265356164326637663862346233636432393531
          38303139663338613136626130346661663633366361616231306539373337303236313134663338
          6363613061386532303361303738393334326635313066363436
