---
consul_group_name: consul
consul_gather_server_facts: true
consul_datacenter: dc1
consul_raw_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  63613934313736666237323331613533616465386237316661353733306430333631616237373863
  3463333935303039346433356538303063643364396230330a643834663336393637373934663961
  30353436613363626331333438616635646235373866376362376365313865353834623564323532
  6562383232313665610a363135333064356132313230363834393631326433653262666663623738
  63376531303536306138373833343634373735613431666231623332663739636136653737643166
  3266623161333765383264653832656634636135613534613361
