---
general_environment: development

general_dns_servers:
  - 192.168.178.95
  - 192.168.178.96

general_ssh_port: 22
general_admin_ssh_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  39623633393233623732663764653639636134343133643361356566323539343834666262353031
  3039353932343930313466613432623435356436376563380a326331313765623961313835363532
  37373732663963346238383037653338663939343334346263343232366262303463363565623234
  6136373234376565630a346162333933316433323563343066306363393332636164373964656437
  34306664336239383533343537623666663330646262373936613262633032373137333735313639
  34643837646239396166353437373366376430366335373637356432666636663735623436396361
  63353234663033373965363564313636653965353466353534313365393039373033653164383564
  37656161323537623163623233653236633232653863656164326431383863326665346164663166
  6266

general_root_setup_enabled: true
general_root_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64643530333431303661346561303639343065363737653932326539356633393839333030363863
  3936666137393366666464396465663336636439306564640a386366376264316366363630343738
  62313731323431306565336265313139313635626632386338363965633463353636336231303265
  3633643461666462390a393834396566343837316230396234613238353635656434353836316231
  6663

general_root_password_salt: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64643530333431303661346561303639343065363737653932326539356633393839333030363863
  3936666137393366666464396465663336636439306564640a386366376264316366363630343738
  62313731323431306565336265313139313635626632386338363965633463353636336231303265
  3633643461666462390a393834396566343837316230396234613238353635656434353836316231
  6663
