---
general_environment: development

general_dns_servers:
  - 192.168.178.95
  - 192.168.178.96

general_ssh_port: 22
general_admin_ssh_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  39623633393233623732663764653639636134343133643361356566323539343834666262353031
  3039353932343930313466613432623435356436376563380a326331313765623961313835363532
  37373732663963346238383037653338663939343334346263343232366262303463363565623234
  6136373234376565630a346162333933316433323563343066306363393332636164373964656437
  34306664336239383533343537623666663330646262373936613262633032373137333735313639
  34643837646239396166353437373366376430366335373637356432666636663735623436396361
  63353234663033373965363564313636653965353466353534313365393039373033653164383564
  37656161323537623163623233653236633232653863656164326431383863326665346164663166
  6266

general_root_setup_enabled: true
general_root_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  65363836653866336438396566363632366333646534373433653038666361613231303236653033
  3365343237393639663930363965373035336666396237360a336636313363326238636136383137
  34353033623536333638323335656639376639313238646536313666366432366430656531366131
  3463666562663831660a376665376132303633333663323538363136396564323364313334323565
  6438

general_root_password_salt: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  39393966353263663661386634383233633264643336633434383634643661363539633163343631
  3735613036356664303838336431663739333538346433370a616464316266643232396339303930
  30366265613562316232626534383131636466373265306539336563343961663430613136323662
  6166666463653534370a626238613038383633366539346263613063316464303665616430633666
  3330
