minio_user: netbox
minio_group: netbox

minio_install_server: false

minio_api_user: netbox-backups
minio_api_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      37646664343437366362633031303239666562626331396632653932373939343335663334333935
      3138393536343638343330646362613165636263356663380a366337383162313066363165643232
      32613766326636623034623962653562386230323035323031663833373634393066616234613939
      3639633965356465310a353130303563376464353138366266323034383931646435313461316430
      39363161626630646164646564303932623430373132656264303132316133376637
minio_api_url: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34613762396137666533323830666234383337303231393661323639633334323931376263653262
          3635613935393934333831666333636431393664306530630a663132356433316137323363646235
          38306163666163316434656136636636643863333862313363363833306264376331373265653034
          6463333133353036320a326366656536636664633164366530353061366136386137646333303965
          39373462343064353965616564343165323038343437633335306232396263306530366333346439
          6230623233373337653263343363323435383939656266636239
