---
general_ufw_ports:
  - port: "{{ general_ssh_port }}"
    proto: tcp
    state: enabled
    comment: "SSH"

  - port: "8500"
    proto: tcp
    state: enabled
    comment: "HAPROXY - Consul"

  - port: "9100"
    proto: tcp
    state: enabled
    comment: "Node Exporter"
