---
vault_agent_user: "haproxy"
vault_agent_group: "haproxy"
vault_agent_vault_addr: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61656535656430383463356530306165373736383064306564336263633335383535326561313464
          3531353766643832323136636166633065313138663438360a366239373463356334663537643066
          36353030386535643661663338626565363732623365336565646266346466613166326530343534
          3937393163396632340a316563663133613435623833623061383961633737663466363939346634
          61393238316537343331373030326439663232666366613565303162623034313466326230336334
          6664353238323032306336393939323338356539336638306136
