---
bind9_authoritative: true
bind9_forward: true
bind9_recursor: true
bind9_forward_servers:
  - 1.1.1.1
bind9_slaves:
  - 192.168.178.96
bind9_our_neighbors:
  - 192.168.178.96

bind9_zones_dynamic:
  - name: bluecore
    serial: 2025081124
    admin: noemail.bluecore
    ns_records:
      - dns-01.redstone
      - dns-02.redstone
    rrs:
      - label: grafana
        type: A
        rdata: 192.168.178.249
      - label: longhorn
        type: A
        rdata: 192.168.178.249
  - name: redstone
    serial: 2025081124
    admin: noemail.redstone
    ns_records:
      - dns-01.redstone
      - dns-02.redstone
    rrs:
      - label: netbox-01
        type: A
        rdata: 192.168.178.91
      - label: consul-01
        type: A
        rdata: 192.168.178.92
      - label: consul-02
        type: A
        rdata: 192.168.178.93
      - label: consul-03
        type: A
        rdata: 192.168.178.94
      - label: dns-01
        type: A
        rdata: 192.168.178.95
      - label: dns-02
        type: A
        rdata: 192.168.178.96
      - label: pve-01
        type: A
        rdata: 192.168.178.81
      - label: loadbalancer-01
        type: A
        rdata: 192.168.178.101
      - label: loadbalancer-02
        type: A
        rdata: 192.168.178.100
      - label: gh-runner-01
        type: A
        rdata: 192.168.178.102
      - label: gh-runner-02
        type: A
        rdata: 192.168.178.103
      - label: monitoring-01
        type: A
        rdata: 192.168.178.104
      - label: vault-01
        type: A
        rdata: 192.168.178.105
      - label: vault-02
        type: A
        rdata: 192.168.178.107
      - label: vault-03
        type: A
        rdata: 192.168.178.106
      - label: k8s-master-01
        type: A
        rdata: 192.168.178.108
      - label: k8s-node-01
        type: A
        rdata: 192.168.178.109
      - label: k8s-node-02
        type: A
        rdata: 192.168.178.110
      - label: keycloak-01
        type: A
        rdata: 192.168.178.111
  - name: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      38383063336632363530623037366536626230303732633363363538363936643832376136313464
      3363343930636132386331646466663435383430633234620a643139613433313838393064373036
      37366537373566666639393364393638356535643437376539623466353639366334343265663631
      6266643466343861610a373932386262326437616136333233643566663762313031393561396233
      64613636643062306532323134323265333666613366303034643231306532643963
    serial: 2025081106
    admin: noemail.redstone
    ns_records:
      - dns-01.redstone
      - dns-02.redstone
    rrs:
      - label: consul
        type: A
        rdata: 192.168.178.250
      - label: vault
        type: A
        rdata: 192.168.178.250
      - label: docker
        type: A
        rdata: 192.168.178.250
      - label: keycloak
        type: A
        rdata: 192.168.178.250
