---
backup_gpg_signing_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62623331306330633632303630383062356430633661656134356662376663393662636237353766
          3465623666376663623335363937343332666438623637620a363239306361666438323630353664
          64383437383834356562316461386234616362666263636261363038383139353431643236383232
          6532373836396562620a636436336665366333656632316566643334353337373366323136323038
          35623534343136353462376631663931373438363034383662633132313537356536613666613833
          3433363363383032633932623763656130303965343438633831
