apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: bitnami-redis
spec:
  interval: 5m
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: redis
        namespace: bitnami-redis
      chart: redis
      version: "25.0.0"
