apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/longhorn
patches:    
  - target:
      kind: HelmRelease
      name: longhorn-release
    patch: |
      - op: add
        path: /spec/values/defaultSettings/defaultDataPath
        value: /mnt/longhorn
