---
general_debian_extra_packages:
  - gpg

general_ufw_ports:
  - port: "{{ general_ssh_port }}"
    proto: tcp
    state: enabled
    comment: "SSH"

  - port: "9100"
    proto: tcp
    state: enabled
    comment: "Node Exporter"
