apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastucture-controllers
  namespace: flux-system
spec:
  interval: 30s
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/infrastructure/controllers/redstone-01-dev
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastucture-configs
  namespace: flux-system
spec:
  interval: 30s
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: infrastucture-controllers
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/infrastructure/configs/redstone-01-dev
  prune: true
