---
backup_gpg_signing_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62373030363238396437313365333438656635393832356462656264363037313239333530323633
          3532316437666461653730333961386234383936383937610a633835363035666639313733316665
          34343766343035663532633832613034386163316562336534303339386230356339313565373665
          6234353038303135640a306664396236356462373262653533323336373332336534393962653131
          32623632383466616261303261323766623432393435616662306265626165643739383231356639
          6463396537616265306232333766663161653536633531353333
