---
backup_netbox_user: netbox
backup_netbox_group: netbox
backup_netbox_script_path: "/opt/netbox_scripts/netbox_backup.sh"
backup_minio_alias: "minio"
backup_minio_bucket: "netbox-backups"

backup_netbox_db_container: "netbox-git-postgres-1"
backup_netbox_db_user: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  33313131333661333534663831613932613538656666636131653166333161303931636435613936
  3239616464373564663661666332316365313935393464640a326437633166666432626634386162
  33303330663037326236353433346537343633386436333464336562346338633639303061383661
  6433643131323239610a633563396133623639373133643639643265393336366630376532333261
  3135

backup_netbox_db_name: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  39333663353938383433396264376332313466383933343164623266326364666439666431386166
  3463346665633231363935623838383266306237663566360a326366626166386436313438393637
  64363230336535313136626162353738623438356634653737656666663964326432653539316630
  6435633130336338350a366164376536613935623937323162643065376630643536613565336538
  3432
