---
backup_gpg_signing_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62643437323838336138646132363237316231353066646637636239623865646135376330373731
          6161376366336161626438646261313637386266626630620a393766663463303338346233363564
          32613465383837643332303239313238306366343637326239313761643636303231343236333834
          3663653132626664620a623937663432343335633163326135356662663632343663323237383866
          35633332323639316630393337366466366261333764363464303661366466666261356437346264
          3063366633343735623533633764633965313761663930323333
