apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alertbridge-frontend-ingress
  namespace: alertbridge
spec:
  ingressClassName: nginx
  rules:
    - host: alertbridge.bluecore
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: alertbridge-frontend
                port:
                  number: 80
