---
general_ufw_ports:
  - port: "{{ general_ssh_port }}"
    proto: tcp
    state: enabled
    comment: "SSH"

  - port: "9000"
    proto: tcp
    state: enabled
    comment: "Minio"

  - port: "9001"
    proto: tcp
    state: enabled
    comment: "Minio Ui"

  - port: "9100"
    proto: tcp
    state: enabled
    comment: "Node Exporter"
