---
consul_node_role: client
consul_services:
  - name: node_exporter
    id: node_exporter
    port: 9100
    address: "{{ general_hostname }}"
    checks:
      - id: node_exporter_health
        name: Node Exporter HTTP Health Check
        http: http://127.0.0.1:9100/metrics
        interval: 10s
        timeout: 1s
    tags:
      - metrics
      - node
      - prometheus
  - name: bind_exporter
    id: bind_exporter
    port: 9119
    address: "{{ general_hostname }}"
    checks:
      - id: bind_exporter_health
        name: Bind Exporter HTTP Health Check
        http: http://127.0.0.1:9119/metrics
        interval: 10s
        timeout: 1s
    tags:
      - metrics
      - bind
      - prometheus
