---
general_ufw_ports:
  - port: "{{ general_ssh_port }}"
    proto: tcp
    state: enabled
    comment: "SSH"

  - port: "53"
    proto: tcp
    state: enabled
    comment: "DNS"
  - port: "53"
    proto: udp
    state: enabled
    comment: "DNS"

  - port: "8301"
    proto: tcp
    state: enabled
    comment: "Consul LAN"
  - port: "8301"
    proto: udp
    state: enabled
    comment: "Consul LAN"

  - port: "8500"
    proto: tcp
    state: enabled
    comment: "Consul HTTP"

  - port: "8600"
    proto: tcp
    state: enabled
    comment: "Consul DNS"
  - port: "8600"
    proto: udp
    state: enabled
    comment: "Consul DNS"

  - port: "9100"
    proto: tcp
    state: enabled
    comment: "Node Exporter"

  - port: "9119"
    proto: tcp
    state: enabled
    comment: "Bind Exporter"
