---
general_ufw_ports:
  - port: "{{ general_ssh_port }}"
    proto: tcp
    state: enabled
    comment: "SSH"

  - port: "53"
    proto: tcp
    state: enabled
    comment: "DNS"
  - port: "53"
    proto: udp
    state: enabled
    comment: "DNS"
