---
general_debian_extra_packages:
  - unzip
  - jq
  - gpg
  # debian 13 packages
  - acl
  - liblttng-ust1t64
  - libkrb5-3
  - zlib1g
  - libssl3
  - libicu76

general_ufw_ports:
  - port: "{{ general_ssh_port }}"
    proto: tcp
    state: enabled
    comment: "SSH"

  - port: "9100"
    proto: tcp
    state: enabled
    comment: "Node Exporter"
