---
runner_user: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64363632356135343662363165356363623233646133393835333864633537326434616234613734
          3164636430393531313764346461363562373831646638640a386564393939323533336364396665
          65343731643838306664346534616235356363393431653062333263353936386438623066656233
          3465653132643735630a636364336130646336323339636130336666386530376635336432383865
          6530


access_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39663664656435663165663866316661663137326633623364613234636139316231343931353038
          3933656133326538323266313939373135373437326436320a333964623835636262626665663061
          34346665343931616362616633393965376439653163636261363439353463316238636438616163
          3430343466343136360a306530313866616562373835616135363636653165366634376234316235
          61313761626531323136316130613764363939653232363964386164663366303435633435643430
          35363434373231336632343264616264616465306637326466323133653262623938313335356131
          35333761363634656236613863326564643763353063633866363563303237656634643233636435
          62356237383436376332616363626531313563666538323166323936396432626135366432376439
          3235

github_account: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64636332643835326562313936626366316136666538666432356130356336383538396564346230
          3634383963343237366466343536623066313532326638630a623962313631386238326536633766
          35373064313838663737356232616537306533373936303533323939316632636639643530333466
          3362633035666637650a313830363866323336313439373338616262386331323230363364626538
          3066

github_repo: "homelab"
runner_version: "2.321.0"
runner_dir: "/opt/actions-runner-homelab"
