---
# Needs local vault cli connection
#
# vars:
# backup_vault_user: "vault"
# backup_vault_group: "vault"
# backup_approle: "backup"
# backup_script_path: "/opt/vault_scripts/vault_backup.sh"
# backup_vault_addr: "https://{{ inventory_hostname }}:8200"
# backup_minio_alias: minio
# backup_minio_bucket: "bucket"
#
- name: Ensure vault cli is working
  delegate_to: localhost
  run_once: true
  block:
    - name: Check vault login
      ansible.builtin.command:
        cmd: "vault login $VAULT_TOKEN"
      register: "assert_vault_token"
      ignore_errors: true
      changed_when: false

    - name: Check vault cli output
      ansible.builtin.assert:
        that:
          - assert_vault_token.rc == 0
        fail_msg: "vault cli connection failed"

- name: Prepare approle login
  ansible.builtin.include_tasks:
    file: ./vault-deploy-approle-login.yml
  vars:
    approle: "{{ backup_approle }}"
    owner: "{{ backup_vault_user }}"
    group: "{{ backup_vault_group }}"
  register: vault_approle_login

- name: Ensure backup script dir exists
  become: true
  ansible.builtin.file:
    path: /opt/vault-scripts
    state: directory
    recurse: true
    owner: "{{ backup_vault_user }}"
    group: "{{ backup_vault_group }}"
    mode: '0700'

- name: Ensure vault-backup log exists
  become: true
  changed_when: false
  ansible.builtin.file:
    path: "/var/log/vault-backup.log"
    state: touch
    mode: "0640"
    owner: "{{ backup_vault_user }}"
    group: "logs"

- name: Copy backup script
  become: true
  ansible.builtin.template:
    src: backup/vault-backup.sh.j2
    dest: "{{ backup_script_path }}"
    owner: "{{ backup_vault_user }}"
    group: "{{ backup_vault_group }}"
    mode: '0700'

- name: Setup cronjob
  become: true
  ansible.builtin.cron:
    name: Vault backup
    user: "{{ backup_vault_user }}"
    state: present
    job: "{{ backup_script_path }}"
    hour: "*/12"
