apiVersion: v1
kind: Service
metadata:
  name: alertbridge-backend
spec:
  selector:
    app: alertbridge-backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
