vault_address: "0.0.0.0"
server_url: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  31663461376561386539636561636666633430663363666133343565363666623730646232356436
  6539383864353430346533343332656632323035623037630a353363313330363931323332636637
  34353430333339313665633038646539353066316632336534613066303733646133306539393861
  3437336564323936390a316666353735623335303531346238613162303366613561386262323066
  66393334386265396165643132613336353466636430306533366337303439393064
vault_api_addr: "https://vault.{{ server_url }}"
vault_tls_disable: 'false'
vault_tls_copy_keys: "false"
vault_tls_private_path: "/etc/vault/tls"
vault_tls_certs_path: /etc/vault/tls
vault_tls_key_file: "server.key"
vault_tls_cert_file: "fullchain.pem"
vault_dotfile_disable: true
