---
- name: Install dns
  hosts: dns
  gather_facts: true
  become: true
  roles:
    - role: reneruprecht.general
    - role: ansible-consul
    - role: systemli.bind9
    - role: grafana.grafana.promtail
    - role: prometheus.prometheus.node_exporter
    - role: prometheus.prometheus.bind_exporter
