---
- name: Install gh-runner
  hosts: gh_runner
  become: true
  roles:
    - role: reneruprecht.general
    - role: ansible-consul
    - role: monolithprojects.github_actions_runner
    - role: geerlingguy.docker
    - role: geerlingguy.nodejs
    - role: grafana.grafana.promtail
    - role: prometheus.prometheus.node_exporter
