---
- name: Install gh-runner
  hosts: gh_runner
  become: true
  roles:
    - role: reneruprecht.general
    - role: monolithprojects.github_actions_runner
    - role: geerlingguy.docker
    - role: geerlingguy.nodejs
