---
- name: Install monitoring vms
  hosts: monitoring
  gather_facts: true
  become: true
  roles:
    - role: reneruprecht.general
    - role: grafana.grafana.loki
    - role: grafana.grafana.promtail
    - role: prometheus.prometheus.prometheus
    - role: prometheus.prometheus.node_exporter
    - role: grafana.grafana.grafana
    - role: ansible-consul
