---
acme_user: haproxy
acme_group: haproxy

acme_vault_addr: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61656535656430383463356530306165373736383064306564336263633335383535326561313464
          3531353766643832323136636166633065313138663438360a366239373463356334663537643066
          36353030386535643661663338626565363732623365336565646266346466613166326530343534
          3937393163396632340a316563663133613435623833623061383961633737663466363939346634
          61393238316537343331373030326439663232666366613565303162623034313466326230336334
          6664353238323032306336393939323338356539336638306136

acme_vault_push_enabled: true

acme_staging: false

acme_account_email: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  37646334383038393562623861313062363064663664633963333436646462363635646566326231
  3332393463363361636530303137313636363531373236640a333335353262363036323334306465
  33643866633135313034663631353263386130376561313664636233636234336265326165393135
  3166613932653465320a656135623966636338646339663561366366636138666132643534393533
  36376166323562313237333361616637623431666435626138363961353038613530

acme_dns_provider_api_keys:
  CF_Token: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    35343331643361633032323262333238633337666232373232343765306365363136653634376631
    3637343436623234653237613236613631353031373332390a613435656565316637373536646231
    64313333326665646635343863356464363863346666663663666366313263333330646139633336
    3038376538663536300a653739633163643062623133336135323838653264616135643363383138
    34333665303364623939333533646464623162646564356361326662356438366162623633353965
    3638636333343765303361363164323963623564306538653139
  CF_Email: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    30373164343333373836383731356237356634626366333135396632393631343564343064633362
    6531643232373662313639363132366438383932663737300a393835316237383864613062303964
    38626638653036353132663233633039653339343834343664646134373365373961363935393539
    3939653966353734620a666434326365326131633965336666663335636163656661373934393732
    32356331373562383633386232386432393633616661376231613361346637666332
acme_cert_domains:
  - domains:
      - !vault |
        $ANSIBLE_VAULT;1.1;AES256
        62306432323461393466636630616632366361626630303437373861353734336264643965613866
        3763613834383565313762306639613261313266653735310a303437386664613835313562613965
        39656433616136363263323462353630386334316534613430613839343135303432363637356564
        3339396432633431640a616439326661353661393536383963663462636638373236383865363636
        63616235663837333263623765316333613231383039383131346461613234343966
