---
collections:
  - name: community.general
  - name: ansible.utils
    version: 2.6.1
  - name: ansible.windows
    version: 1.13.0
  - name: community.windows
    version: 2.1.0
  - name: grafana.grafana
    version: 6.0.6
  - name: prometheus.prometheus
    version: 0.27.3
roles:
  - name: reneruprecht.acme
    src: "https://github.com/reneruprecht/ansible-role-acme"
    scm: git
    version: main
  - name: reneruprecht.general
    src: "https://github.com/reneruprecht/ansible-role-general"
    scm: git
    version: main
  - name: reneruprecht.kubernetes
    src: "https://github.com/reneruprecht/ansible-role-kubernetes"
    scm: git
    version: main
  - src: https://github.com/ansible-community/ansible-vault.git
    name: ansible-community.ansible-vault
    scm: git
    version: master
  - name: geerlingguy.nfs
    version: "2.1.0"
  - name: geerlingguy.nodejs
    version: "7.0.0"
  - name: geerlingguy.docker
    version: "7.4.7"
  - name: monolithprojects.github_actions_runner
    version: "1.26.0"
    src: "https://github.com/MonolithProjects/ansible-github_actions_runner"
  - name: tinslice.ansible-role-disks
    src: "https://github.com/tinslice/ansible-role-disks"
    scm: git
    version: master
  - src: https://github.com/ansible-collections/ansible-consul.git
    name: ansible-consul
    scm: git
    version: master
  - src: https://github.com/robertdebock/ansible-role-haproxy.git
    name: robertdebock.haproxy
    scm: git
    version: "4.8.7"
  - src: https://github.com/evrardjp/ansible-keepalived.git
    name: evrardjp.keepalived
    scm: git
    version: "8.2.0"
  - src: https://github.com/systemli/ansible-role-bind9.git
    name: systemli.bind9
    scm: git
    version: "1.7.1"
