env_no_log: true
environment_vars:
  MINIO_ROOT_USER: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    34343866633064643836373332303166663965626237646439616439323637333761633434356638
    6364316562633637643963653434393562653737346235320a323836353239333564643866353863
    36373636373234626336383664623366363764663863643031623636663363346234396131653866
    3261363061666438350a303762653531303834373364323263643732313866373762343432396235
    3530

  MINIO_ROOT_PASSWORD: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    31373030653534333930646562303237383738643533396131373563643939313366643134396363
    3263613937633436653931313434303336323462633764320a303936616563633066616563643566
    36303434326434336530623337363463393861383038333764636435633232636636336364303634
    3435306462626662630a366164313961353535396437306466303633663837656139646431363866
    34353435363730633062323330623237393837376438663030666563396634656235

  POSTGRES_USER: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    38656631343034383563333135623563396461376363383238633762646632383963346335333233
    6637363861336564643565643634616533333564373666380a366163646635313066333031316331
    32633466663666326136643731636132306239623734363565636339343966343839323633666130
    6337366665386532620a343837656563383935616139623430336163313136383365646166616364
    6135

  POSTGRES_PASSWORD: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    39333664636537333563626235386161303939396666666462666461336530346466653061663861
    3065383338366564326431353661306366623461386363350a313339656462636433323263373562
    39633336353634383938376366363761313865336565643761356263313565306239636138383832
    3738366235313232610a333161363831636437656634616263303637653132333763383765326438
    6531

  POSTGRES_DB: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    39313965616434373833343930323432396266373265366637303637376634613365323863343163
    6163326132323231363864353831383230323533316132360a306562313264306237313736346539
    63646630333332346262346536623539346634363564666561323334366333656135396532373334
    3439656232613534630a396131353861346332643535376230613630663662633136613533636463
    6663

  PGADMIN_DEFAULT_EMAIL: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    31633966396637393264383462313066343266326633623535373737656330656337373261373536
    6631613630653163353464623630353638373037346131320a343562343038663839383233643039
    66666434333234633463623866623563376531303662393335623637636134353932623831396665
    3436366635366630610a366635326466306364613732666135643533373734656565383735663265
    32366637373565386339333534363231333265386233653064613666646536663937

  PGADMIN_DEFAULT_PASSWORD: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    32646265613166393461353666346536356234663235626632336364353261613139666336343731
    3936336339356562343864316463646536303266613336370a393161336165643536336230303030
    31363231326238306265393738393130653435353461363831643665623237643133303532663834
    3534333232623164310a343738633165633362386366316464383530393962653062613665333430
    6230

  PGADMIN_DISABLE_SESSION_SECURITY: "true"
