apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: monitoring
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = ''
    root_url = http://monitoring.redstone/grafana
    serve_from_sub_path = true
    [auth.generic_oauth]
    enabled= True
    name= Keycloak-OAuth
    allow_sign_up= True
    client_id= $__file{/etc/secrets/auth_generic_oauth/client_id}
    client_secret= $__file{/etc/secrets/auth_generic_oauth/client_secret}
    scopes= openid email profile offline_access roles
    email_attribute_path= email
    login_attribute_path= username
    name_attribute_path= full_name
    auth_url= $__file{/etc/secrets/auth_generic_oauth/auth_url}
    token_url= $__file{/etc/secrets/auth_generic_oauth/token_url}
    api_url= $__file{/etc/secrets/auth_generic_oauth/api_url}
    role_attribute_path= contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'
