---
backup_consul_user: "consul"
backup_consul_group: "consul"
backup_consul_script_path: "/opt/consul-scripts/consul-backup.sh"
backup_minio_alias: "minio"
backup_minio_bucket: "consul-backups"
backup_gpg_recipient: "main@redstone"
