---
general_debian_extra_packages:
  - acl

general_ufw_ports:
  - port: "{{ general_ssh_port }}"
    proto: tcp
    state: enabled
    comment: "SSH"

  - port: "8300"
    proto: tcp
    state: enabled
    comment: "Consul SERVER"

  - port: "8301"
    proto: tcp
    state: enabled
    comment: "Consul LAN"
  - port: "8301"
    proto: udp
    state: enabled
    comment: "Consul LAN"

  - port: "8302"
    proto: tcp
    state: enabled
    comment: "Consul WAN"
  - port: "8302"
    proto: udp
    state: enabled
    comment: "Consul WAN"

  - port: "8500"
    proto: tcp
    state: enabled
    comment: "Consul HTTP"

  - port: "8503"
    proto: tcp
    state: enabled
    comment: "Consul GRPC TLS"

  - port: "8600"
    proto: tcp
    state: enabled
    comment: "Consul DNS"
  - port: "8600"
    proto: udp
    state: enabled
    comment: "Consul DNS"

  - port: "9100"
    proto: tcp
    state: enabled
    comment: "Node Exporter"

  - port: "9107"
    proto: tcp
    state: enabled
    comment: "Consul Exporter"
