---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-cert
  namespace: longhorn-system
spec:
  secretName: longhorn-cert-tls
  commonName: bluecore
  dnsNames:
    - longhorn.bluecore
  issuerRef:
    name: pki-int-bluecore
    kind: ClusterIssuer
