---
backup_gpg_signing_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32636163386436663562303565643763383436386630653565666339336334616562366433616465
          3231396434306338363237346530396230393836383865610a366130323864623637363764383439
          37313962653633303636386466363638636662336232613139303765396365323738616630316330
          6437396637336561320a616563343661353062666337396632666638336639323161383861383239
          36323963323237376437663738333930343266653662356334306535663430336135643335303532
          3966373833376361393030303732346635353866656139323937

