---
minio_user: "backup"
minio_group: "backup"

minio_api_user: minio
minio_api_password: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    35306134656539303935623465343335363465366364313738646235376134363536323363353136
    3766663036663932643234303331623832356637303939390a613631323963343062623263386166
    63356635623531616138626161643235343263333738633637356262333063373130626565316236
    3239316365306266390a373035336262613966383132316462343463646462326464643038366166
    3530
minio_api_url: "http://localhost:9000"

minio_create_data_dirs: true
minio_data_dirs:
  - /data1

minio_users:
  - name: vault-backups
    password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37646664343437366362633031303239666562626331396632653932373939343335663334333935
          3138393536343638343330646362613165636263356663380a366337383162313066363165643232
          32613766326636623034623962653562386230323035323031663833373634393066616234613939
          3639633965356465310a353130303563376464353138366266323034383931646435313461316430
          39363161626630646164646564303932623430373132656264303132316133376637
    policy_type: write
    buckets:
      - name: vault-backups
        state: present
        versioning: true
  - name: consul-backups
    password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37646664343437366362633031303239666562626331396632653932373939343335663334333935
          3138393536343638343330646362613165636263356663380a366337383162313066363165643232
          32613766326636623034623962653562386230323035323031663833373634393066616234613939
          3639633965356465310a353130303563376464353138366266323034383931646435313461316430
          39363161626630646164646564303932623430373132656264303132316133376637
    policy_type: write
    buckets:
      - name: consul-backups
        state: present
        versioning: true
  - name: netbox-backups
    password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37646664343437366362633031303239666562626331396632653932373939343335663334333935
          3138393536343638343330646362613165636263356663380a366337383162313066363165643232
          32613766326636623034623962653562386230323035323031663833373634393066616234613939
          3639633965356465310a353130303563376464353138366266323034383931646435313461316430
          39363161626630646164646564303932623430373132656264303132316133376637
    policy_type: write
    buckets:
      - name: netbox-backups
        state: present
        versioning: true
