---
minio_docker_tag: 'RELEASE.2025-09-07T16-13-09Z'
minio_root_user: minio
minio_root_password: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    35306134656539303935623465343335363465366364313738646235376134363536323363353136
    3766663036663932643234303331623832356637303939390a613631323963343062623263386166
    63356635623531616138626161643235343263333738633637356262333063373130626565316236
    3239316365306266390a373035336262613966383132316462343463646462326464643038366166
    3530
