---
backup_gpg_signing_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32346461306539306432356664616464616261326439353566393766346232623635613435333364
          3631356535323030653663383566326136313539666639660a363132346637616166343634333364
          62333765313831383665393733656339366464393833316136303731663538353965393561353965
          3632613736313465630a373831363430363730336661306335386434666230383965613438356363
          65616263666666373035623561356462313033316135646466363730356235653465303765303831
          6630326138633165383230656665326165303034613030623763
